name: Build and Run Automated Tests
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - master

jobs:
  ci:
    name: ${{ matrix.name }}
    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        name: [clang, gcc]
        os: [ubuntu-latest]
        include:
          - name: clang
            cc: clang-8
            cxx: clang++-8

          - name: gcc
            cc: gcc-9
            cxx: g++-9
    steps:
      - uses: actions/checkout@v1
      - name: Setup the container.
        run: docker pull nashtrash/isd-base
      - name: Start the container.
        run: docker run -itd -e CC=${{ matrix.cc }} -e CXX=${{ matrix.cxx }} --name build nashtrash/isd-base
      - name: Copy repo and deps over.
        run: docker cp . build:/repo
      - name: Configure.
        run: docker exec -t build cmake -H/repo -B/build
      - name: Build.
        run: docker exec -t build cmake --build /build
      - name: Run.
        run: docker exec -t build bash -c "cd /repo/bin && ./testing"

  linter:
    name: linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup the container.
        run: docker pull nashtrash/isd-base
      - name: Start the container.
        run: docker run -itd --name build nashtrash/isd-base
      - name: Copy repo and deps over.
        run: docker cp . build:/repo
      - name: Set run permissions
        run: chmod +x .github/workflows/linter.sh
      - name: Run the linter
        run: .github/workflows/linter.sh
